name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install system dependencies
      run: |
        sudo apt-get install -y portaudio19-dev
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --show-source --statistics
    - name: Format check with black
      run: |
        pip install black
        black --check .
    - name: Run basic tests
      run: |
        python -c "import pyaudio; print('PyAudio version:', pyaudio.__version__)"
        python -c "from tencentcloud.common import credential; print('SDK import success')" 