name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        cache: 'pip'
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev python3-pyaudio ffmpeg
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create test data directory
      run: |
        mkdir -p test_data
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics
    - name: Format check with black
      run: |
        black --check .
    - name: Run basic tests
      run: |
        python -c "import pyaudio; print('PyAudio version:', pyaudio.__version__)"
        python -c "from tencentcloud.common import credential; print('SDK import success')"
        ffmpeg -version
    - name: Run unit tests
      env:
        TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
      run: |
        pip install pytest
        pytest tests/ -v 